#import <ParseKit/PKSParser.h>

enum {
    GREEDYFAILURENESTED_TOKEN_KIND_LCURLY = 14,
    GREEDYFAILURENESTED_TOKEN_KIND_RCURLY,
    GREEDYFAILURENESTED_TOKEN_KIND_COLON,
};

@interface GreedyFailureNestedParser : PKSParser

@end

