#import <ParseKit/PKSParser.h>

enum {
    JSON_TOKEN_KIND_SCRIPTTAGNAME = 14,
    JSON_TOKEN_KIND_STYLETAGNAME,
    JSON_TOKEN_KIND_DOCTYPE,
    JSON_TOKEN_KIND_LT,
    JSON_TOKEN_KIND_PROCINSTR,
    JSON_TOKEN_KIND_EQ,
    JSON_TOKEN_KIND_FWDSLASH,
    JSON_TOKEN_KIND_GT,
};

@interface JSONParser : PKSParser

@end

