#import <ParseKit/PKSParser.h>

enum {
    TREEOUTPUT_TOKEN_KIND_INT = 14,
    TREEOUTPUT_TOKEN_KIND_DOUBLE,
    TREEOUTPUT_TOKEN_KIND_CHAR,
    TREEOUTPUT_TOKEN_KIND_OPEN_BRACKET,
    TREEOUTPUT_TOKEN_KIND_COMMA,
    TREEOUTPUT_TOKEN_KIND_BAR,
    TREEOUTPUT_TOKEN_KIND_VAR,
    TREEOUTPUT_TOKEN_KIND_ARRAY,
    TREEOUTPUT_TOKEN_KIND_CLOSE_BRACKET,
    TREEOUTPUT_TOKEN_KIND_FLOAT,
    TREEOUTPUT_TOKEN_KIND_SEMI_COLON,
};

@interface TreeOutputParser : PKSParser

@end

