#import <ParseKit/PKSParser.h>

enum {
    TREEOUTPUT_TOKEN_KIND_FALSELITERAL = 14,
    TREEOUTPUT_TOKEN_KIND_CLOSECURLY,
    TREEOUTPUT_TOKEN_KIND_OPENBRACKET,
    TREEOUTPUT_TOKEN_KIND_NULLLITERAL,
    TREEOUTPUT_TOKEN_KIND_COMMA,
    TREEOUTPUT_TOKEN_KIND_TRUELITERAL,
    TREEOUTPUT_TOKEN_KIND_CLOSEBRACKET,
    TREEOUTPUT_TOKEN_KIND_OPENCURLY,
    TREEOUTPUT_TOKEN_KIND_COLON,
};

@interface TreeOutputParser : PKSParser

@end

