#import <ParseKit/PKSParser.h>

enum {
    TREEOUTPUT_TOKEN_KIND_CLOSE_BRACKET = 14,
    TREEOUTPUT_TOKEN_KIND_OPEN_BRACKET,
    TREEOUTPUT_TOKEN_KIND_ARRAY,
    TREEOUTPUT_TOKEN_KIND_INT,
    TREEOUTPUT_TOKEN_KIND_BAR,
    TREEOUTPUT_TOKEN_KIND_SEMI_COLON,
};

@interface TreeOutputParser : PKSParser

@end

