#import "PKSParser.h"

enum {
    TOKEN_TYPE_LT = 14,
    TOKEN_TYPE_GT,
    TOKEN_TYPE_EQ,
    TOKEN_TYPE_NE,
    TOKEN_TYPE_LE,
    TOKEN_TYPE_GE,
    TOKEN_TYPE_OPENPAREN,
    TOKEN_TYPE_CLOSEPAREN,
    TOKEN_TYPE_YES,
    TOKEN_TYPE_NO,
    TOKEN_TYPE_DOT,
    TOKEN_TYPE_COMMA,
    TOKEN_TYPE_OR,
    TOKEN_TYPE_AND,
};

@interface ElementParser : PKSParser

@end
