#import <ParseKit/PKSParser.h>

enum {
    EXPRESSIONSYNTAX_TOKEN_KIND_GE = 14,
    EXPRESSIONSYNTAX_TOKEN_KIND_COMMA,
    EXPRESSIONSYNTAX_TOKEN_KIND_OR,
    EXPRESSIONSYNTAX_TOKEN_KIND_LT,
    EXPRESSIONSYNTAX_TOKEN_KIND_LE,
    EXPRESSIONSYNTAX_TOKEN_KIND_EQ,
    EXPRESSIONSYNTAX_TOKEN_KIND_DOT,
    EXPRESSIONSYNTAX_TOKEN_KIND_GT,
    EXPRESSIONSYNTAX_TOKEN_KIND_OPENPAREN,
    EXPRESSIONSYNTAX_TOKEN_KIND_YES,
    EXPRESSIONSYNTAX_TOKEN_KIND_NO,
    EXPRESSIONSYNTAX_TOKEN_KIND_CLOSEPAREN,
    EXPRESSIONSYNTAX_TOKEN_KIND_NE,
    EXPRESSIONSYNTAX_TOKEN_KIND_AND,
};

@interface ExpressionSyntaxParser : PKSParser

@end

