#import <ParseKit/PKSParser.h>

enum {
    TOKEN_KIND_BANG = 14,
    TOKEN_KIND_COLON,
    TOKEN_KIND_HASHSYM,
    TOKEN_KIND_SEMI,
    TOKEN_KIND_COMMA,
    TOKEN_KIND_OPENBRACKET,
    TOKEN_KIND_EQ,
    TOKEN_KIND_DOT,
    TOKEN_KIND_OPENCURLY,
    TOKEN_KIND_GT,
    TOKEN_KIND_CLOSEBRACKET,
    TOKEN_KIND_PIPE,
    TOKEN_KIND_OPENPAREN,
    TOKEN_KIND_FWDSLASH,
    TOKEN_KIND_CLOSECURLY,
    TOKEN_KIND_CLOSEPAREN,
    TOKEN_KIND_AT,
    TOKEN_KIND_TILDE,
};

@interface CSSParser : PKSParser

@end

