#import <ParseKit/PKSParser.h>
enum {
    TOKEN_KIND_ALL = 14,
    TOKEN_KIND_FALSEPREDICATE,
    TOKEN_KIND_NOT_UPPER,
    TOKEN_KIND_OPEN_CURLY,
    TOKEN_KIND_HASH_ROCKET,
    TOKEN_KIND_GE,
    TOKEN_KIND_DOUBLE_AMPERSAND,
    TOKEN_KIND_TRUEPREDICATE,
    TOKEN_KIND_AND_UPPER,
    TOKEN_KIND_CLOSE_CURLY,
    TOKEN_KIND_TRUELITERAL,
    TOKEN_KIND_NE,
    TOKEN_KIND_OR_UPPER,
    TOKEN_KIND_BANG,
    TOKEN_KIND_SOME,
    TOKEN_KIND_IN,
    TOKEN_KIND_BEGINSWITH,
    TOKEN_KIND_LT,
    TOKEN_KIND_EQUALS,
    TOKEN_KIND_CONTAINS,
    TOKEN_KIND_GT,
    TOKEN_KIND_OPEN_PAREN,
    TOKEN_KIND_CLOSE_PAREN,
    TOKEN_KIND_DOUBLE_PIPE,
    TOKEN_KIND_MATCHES,
    TOKEN_KIND_COMMA,
    TOKEN_KIND_LIKE,
    TOKEN_KIND_ANY,
    TOKEN_KIND_ENDSWITH,
    TOKEN_KIND_FALSELITERAL,
    TOKEN_KIND_LE,
    TOKEN_KIND_BETWEEN,
    TOKEN_KIND_EL,
    TOKEN_KIND_NOT_EQUAL,
    TOKEN_KIND_NONE,
    TOKEN_KIND_DOUBLE_EQUALS,
};

@interface TDNSPredicateParser : PKSParser

@end

