#import <ParseKit/PKSParser.h>

enum {
    OKMINICSS_TOKEN_KIND_COLON = 14,
    OKMINICSS_TOKEN_KIND_BOLD,
    OKMINICSS_TOKEN_KIND_ITALIC,
    OKMINICSS_TOKEN_KIND_SEMI_COLON,
    OKMINICSS_TOKEN_KIND_COMMA,
    OKMINICSS_TOKEN_KIND_FONTFAMILY,
    OKMINICSS_TOKEN_KIND_FONTSIZE,
    OKMINICSS_TOKEN_KIND_NORMAL,
    OKMINICSS_TOKEN_KIND_PX,
    OKMINICSS_TOKEN_KIND_COLOR,
    OKMINICSS_TOKEN_KIND_RGB,
    OKMINICSS_TOKEN_KIND_OPEN_CURLY,
    OKMINICSS_TOKEN_KIND_OPEN_PAREN,
    OKMINICSS_TOKEN_KIND_BACKGROUNDCOLOR,
    OKMINICSS_TOKEN_KIND_CLOSE_CURLY,
    OKMINICSS_TOKEN_KIND_CLOSE_PAREN,
};

@interface OKMiniCSSParser : PKSParser

@end

